
name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Maven
      run: mvn versions:set -DnewVersion=1.${{github.run_number}} clean package
    - name: Archive artifacts in current GitHub action run
      uses: actions/upload-artifact@v1
      with:
        name: CloudNet-2_1-WebInterface.jar
        path: WebInterface/target/CloudNet-2_1-WebInterface.jar
    - name: Deploy to GitHub packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mkdir -p ~/.m2
        echo "<settings><servers><server><id>github</id><username>The-Systems</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml


